"""empty message

Revision ID: 23baa0cabd01
Revises: 95ea2fb21103
Create Date: 2026-07-27 19:28:28.357547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23baa0cabd01'
down_revision = '95ea2fb21103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
